#!/usr/bin/env bash
# refresh_known_failures.sh — regenerate tests/KNOWN_FAILING_TESTS.md from current test run.
#
# Usage:
#   scripts/refresh_known_failures.sh
#
# Runs the full pytest suite, writes junit.xml to .harness-test-cache/junit.xml,
# then updates the node-id list in tests/KNOWN_FAILING_TESTS.md.
#
# Environment:
#   HARNESS_REFRESH_PYTEST_ARGS  — extra args passed to pytest (default: empty)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CACHE_DIR="$REPO_ROOT/.harness-test-cache"
JUNIT_XML="$CACHE_DIR/junit.xml"
KNOWN_FILE="$REPO_ROOT/tests/KNOWN_FAILING_TESTS.md"
PYTHON="${PYTHON:-python3}"

mkdir -p "$CACHE_DIR"

echo "=== Running pytest to refresh known-failures cache ==="
echo "Output: $JUNIT_XML"
echo ""

# Run pytest — allow non-zero exit (failures are expected)
set +e
"$PYTHON" -m pytest \
    --junitxml="$JUNIT_XML" \
    --tb=no \
    -q \
    ${HARNESS_REFRESH_PYTEST_ARGS:-} \
    2>&1 | tee /tmp/pytest_refresh_output.txt
PYTEST_RC=$?
set -e

echo ""
echo "pytest exit code: $PYTEST_RC"
echo ""

# Parse failures from junit.xml and rewrite KNOWN_FAILING_TESTS.md
"$PYTHON" - <<'EOF'
import xml.etree.ElementTree as ET
import re
import sys
from pathlib import Path
from datetime import date

repo_root = Path(__file__).resolve().parents[1] if False else Path(".").resolve()
junit_xml = repo_root / ".harness-test-cache" / "junit.xml"
known_file = repo_root / "tests" / "KNOWN_FAILING_TESTS.md"

if not junit_xml.exists():
    print(f"ERROR: {junit_xml} not found", file=sys.stderr)
    sys.exit(1)

tree = ET.parse(str(junit_xml))
root = tree.getroot()
failures = []
for tc in root.iter("testcase"):
    if tc.find("failure") is not None or tc.find("error") is not None:
        classname = tc.get("classname", "")
        name = tc.get("name", "")
        if "/" in classname:
            path_part, _, class_part = classname.rpartition(".")
            if not path_part.endswith(".py"):
                path_part += ".py"
            node_id = f"{path_part}::{class_part}::{name}" if class_part else f"{path_part}::{name}"
        else:
            parts = classname.split(".")
            if parts and parts[-1] and parts[-1][0].isupper():
                class_part = parts[-1]
                path_parts = parts[:-1]
            else:
                class_part = ""
                path_parts = parts
            path = "/".join(path_parts) + ".py"
            node_id = f"{path}::{class_part}::{name}" if class_part else f"{path}::{name}"
        # Strip trailing " - ..." error message suffix
        node_id = re.sub(r' - .*$', '', node_id)
        failures.append(node_id)

failures.sort()
today = date.today().isoformat()

# Count by checking summary line
total = len(failures)
print(f"Found {total} failing tests")

content = f"""# Known Pre-Existing Test Failures (as of v0.9.7)

Last verified: {today}
Generated by: scripts/refresh_known_failures.sh
Environment: Python (system), standard dev requirements
Invocation: `python3 -m pytest --tb=no -q`
Count: {total}

## Notes

- These tests fail when the full suite runs together (test isolation issues, sys.path pollution, or environment requirements not met in this local dev setup).
- Many `scripts/test_*.py` failures require a live installed target directory or specific environment state (they are integration/smoke tests meant for CI with a real install).
- `tests/slash/*` and `tests/smoke/*` failures are pre-existing from before v0.9.7.
- `tests/test_upgrade_dry_run.py::TestUpgradeDryRunNoFalseQuarantine::test_no_quarantine_warning_on_fresh_install` is pre-existing (.roomodes.new conflict).
- `tests/test_skip_upgrade_guard.py::test_v094_to_v097_raises_upgrade_refused` and related: pass in isolation, fail in full-suite run due to sys.path state from other tests. Pre-existing ordering issue.

## Node IDs

```
"""

for f in failures:
    content += f + "\n"
content += "```\n"

known_file.write_text(content, encoding="utf-8")
print(f"Written: {known_file}")
EOF

echo ""
echo "=== Done ==="
echo "Updated: $KNOWN_FILE"
echo "Run 'python3 -m pytest tests/test_known_failures_drift.py' to verify drift gate."
